#!/bin/bash

npm run lint-staged || { echo "Linting failed. Please fix lint errors before committing."; exit 1; }

# Check if lint-staged succeeded
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix lint errors before committing."
  exit 1
fi

# Protect master from accidental commits.
echo "Checking branch name"
branchName=$(git rev-parse --abbrev-ref HEAD)

if [ "$branchName" == "main" ] || [ "$branchName" == "master" ]; then
  echo "🚫 Commit directly to master or main branch is not allowed!"
  echo "Please create your own branch and use PR." && exit 1
fi

exit 0
