#!/bin/bash

# Protect master from accidental commits.
echo "Checking branch name"
branchName=$(git rev-parse --abbrev-ref HEAD)

if [ "$branchName" == "main" ] || [ "$branchName" == "master" ]; then
  echo "🚫 Commit directly to master or main branch is not allowed!"
  echo "Please create your own branch and use PR." && exit 1
fi

exit 0