#!/bin/bash
# Prevents force-pushing to master

echo "Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "main" ]] || [[ "$BRANCH" == "master" ]]; then
  echo "🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
fi

exit 0
